baseURL = 'https://joshuarlowry.github.io/'  # Replace with your GitHub username
languageCode = 'en-us'
title = 'My 3D Printing Journey'
theme = 'hugo-book'

# Enable Git Info for last modified date
enableGitInfo = true

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true 