baseURL = 'https://joshuarlowry.github.io/3DPrintingAdventures/'  # This will work for both local and GitHub Pages
languageCode = 'en-us'
title = '3D Printing Adventures'
theme = 'hugo-book'

# Enable Git Info for last modified date
enableGitInfo = true

[params]
  BookTheme = 'dark'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookFavicon = "favicon/3d-printer-svgrepo-com.png"
  BookHomePageURL = "/" 

[mediaTypes]
  [mediaTypes."text/x-gcode"]
    suffixes = ["gcode"]

[outputFormats]
  [outputFormats.GCODE]
    mediaType = "text/x-gcode"
    isPlainText = true
    isHTML = false 