baseURL = 'https://joshuarlowry.github.io/3DPrintingAdventures/'  # Replace with your GitHub username
languageCode = 'en-us'
title = '3D Printing Adventures'
theme = 'hugo-book'

# Enable Git Info for last modified date
enableGitInfo = true

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookFavicon = "/favicon/3d-printer-svgrepo-com.png"
  BookHomePageURL = "/docs/getting-started/" 