baseURL = '/'  # This will work for both local and GitHub Pages
languageCode = 'en-us'
title = '3D Printing Adventures'
theme = 'hugo-book'

# Enable Git Info for last modified date
enableGitInfo = true

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookFavicon = "favicon/3d-printer-svgrepo-com.png"
  BookHomePageURL = "/docs/getting-started/" 